### ISSUE TITLE
Wrongly published copy of the book

### ISSUE THREAD

**Issue by dreispt** [Bachaco-ve/Docs#8]
It came to my attention that you are publishing a copy of my book.
It's my duty to point that it is not ethic to do so, and even disrespectful on the work of the many people involved: not only me, but also all Pack Publishing workers that made it possible and depend on it for their paychecks.

It looks like you would like to work a spanish translation. Those rights are owned by the publisher, but I think we can discuss about that. Please contact me at dgreis (at) sapo.pt.

In the meanwhile, I would appreciate for the original book to be removed form the repo's history.
Thanks in advance for your understanding.

**Comment by dreispt** [comment]
Hello, any comments please?

**Comment by jelitox** [comment]
Hello, @dreispt it's a great pleasure answer you, we sorry for publishing your book, the translate was just a collaborative effort of a group of people how wanna make in spanish personal annotations of a excellent book, the mistake was that we don't have private repos, we are going to remove the files immediately and contact you by email, we are no evil and we are sorry for this incident.

**Comment by dreispt** [comment]
That's OK. Thanks for understanding.

**Comment by dreispt** [comment]
Hi, any news? Let me know in case you need help with Git.

**Comment by dreispt** [comment]
Sorry, ignore that:
I just noticed you already removed it, thanks.

**Comment by jelitox** [comment]
yes, we remove the book, we still are in debt with the apology mail, thanks to you, sorry again for this incident

**Comment by dreispt** [comment]
@jelitox No need for the mail, apologies already taken. The most important thing was that you fixed it.
